// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MultiplayerClient is the client API for Multiplayer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiplayerClient interface {
	GameProcess(ctx context.Context, opts ...grpc.CallOption) (Multiplayer_GameProcessClient, error)
}

type multiplayerClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplayerClient(cc grpc.ClientConnInterface) MultiplayerClient {
	return &multiplayerClient{cc}
}

func (c *multiplayerClient) GameProcess(ctx context.Context, opts ...grpc.CallOption) (Multiplayer_GameProcessClient, error) {
	stream, err := c.cc.NewStream(ctx, &Multiplayer_ServiceDesc.Streams[0], "/Multiplayer/GameProcess", opts...)
	if err != nil {
		return nil, err
	}
	x := &multiplayerGameProcessClient{stream}
	return x, nil
}

type Multiplayer_GameProcessClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type multiplayerGameProcessClient struct {
	grpc.ClientStream
}

func (x *multiplayerGameProcessClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *multiplayerGameProcessClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MultiplayerServer is the server API for Multiplayer service.
// All implementations must embed UnimplementedMultiplayerServer
// for forward compatibility
type MultiplayerServer interface {
	GameProcess(Multiplayer_GameProcessServer) error
	mustEmbedUnimplementedMultiplayerServer()
}

// UnimplementedMultiplayerServer must be embedded to have forward compatible implementations.
type UnimplementedMultiplayerServer struct {
}

func (UnimplementedMultiplayerServer) GameProcess(Multiplayer_GameProcessServer) error {
	return status.Errorf(codes.Unimplemented, "method GameProcess not implemented")
}
func (UnimplementedMultiplayerServer) mustEmbedUnimplementedMultiplayerServer() {}

// UnsafeMultiplayerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiplayerServer will
// result in compilation errors.
type UnsafeMultiplayerServer interface {
	mustEmbedUnimplementedMultiplayerServer()
}

func RegisterMultiplayerServer(s grpc.ServiceRegistrar, srv MultiplayerServer) {
	s.RegisterService(&Multiplayer_ServiceDesc, srv)
}

func _Multiplayer_GameProcess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MultiplayerServer).GameProcess(&multiplayerGameProcessServer{stream})
}

type Multiplayer_GameProcessServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type multiplayerGameProcessServer struct {
	grpc.ServerStream
}

func (x *multiplayerGameProcessServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *multiplayerGameProcessServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Multiplayer_ServiceDesc is the grpc.ServiceDesc for Multiplayer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Multiplayer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Multiplayer",
	HandlerType: (*MultiplayerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GameProcess",
			Handler:       _Multiplayer_GameProcess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/multiplayer.proto",
}
